microsoft/Partner-Center-DotNet-Samples

- sdk/SdkSamples/Orders/GetLineItemActivationLink.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/Subscriptions/CancelSaaSSubscription.cs
- sdk/SdkSamples/Subscriptions/ToggleSubscriptionAutoRenew.cs
New samples:
- Cancel Subscription
- Toggle Autorenew
- Get activation Link
> Adding new samples

- sdk/SdkSamples/Configuration/ScenarioSettingsSection.cs
- sdk/SdkSamples/Invoice/GetBillingLineItemsForOpenPeriodPaging.cs
- sdk/SdkSamples/Invoice/GetEstimatesLinks.cs
- sdk/SdkSamples/Invoice/GetInvoiceLineItems.cs
- sdk/SdkSamples/Invoice/GetInvoiceStatement.cs
- sdk/SdkSamples/Invoice/GetUsageLineItemsForClosePeriodPaging.cs
- sdk/SdkSamples/Invoice/GetUsageLineItemsForOpenPeriodPaging.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
> Trinadh/gtm sdk billing v1.01

- secure-app-model/keyvault/CPVApplication/App.config
- secure-app-model/keyvault/CPVApplication/CPVApplication.csproj
- secure-app-model/keyvault/CPVApplication/Program.cs
- secure-app-model/keyvault/CPVApplication/Properties/AssemblyInfo.cs
- secure-app-model/keyvault/CPVApplication/Utilities/AuthorizationUtilities.cs
- secure-app-model/keyvault/CPVApplication/Utilities/KeyVaultProvider.cs
- secure-app-model/keyvault/CPVApplication/packages.config
- secure-app-model/keyvault/CSPApplication/App.config
- secure-app-model/keyvault/CSPApplication/CSPApplication.csproj
- secure-app-model/keyvault/CSPApplication/Program.cs
- secure-app-model/keyvault/CSPApplication/Properties/AssemblyInfo.cs
- secure-app-model/keyvault/CSPApplication/Utilities/KeyVaultProvider.cs
- secure-app-model/keyvault/CSPApplication/packages.config
- secure-app-model/keyvault/PartnerConsent/App_Start/Startup.Auth.cs
- secure-app-model/keyvault/PartnerConsent/Controllers/HomeController.cs
- secure-app-model/keyvault/PartnerConsent/PartnerConsent.csproj
- secure-app-model/keyvault/PartnerConsent/Web.config
- secure-app-model/keyvault/PartnerConsent/packages.config
Through this pull request the Secure Application Model samples are being updates to include the following 
1. Correct endpoint for resources in China (complete list of addresses can be found at https://docs.microsoft.com/azure/china/resources-developer-guide)
2. Enforced MFA with the partner consent sample through the attention of the amr_values parameter
3. Performed minor code cleanup
4. Update the Nuget packages
> Updates to the Secure Application Model samples

- sdk/README.md
Through this pull request the .NET SDK samples will be added to https://docs.microsoft.com/samples
> Adding the YAML front for the SDK samples

- sdk/SdkSamples/App.config
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
- secure-app-model/README.md
- secure-app-model/keyvault/CPVApplication/App.config
- secure-app-model/keyvault/CPVApplication/CPVApplication.csproj
- secure-app-model/keyvault/CPVApplication/packages.config
- secure-app-model/keyvault/CSPApplication/App.config
- secure-app-model/keyvault/CSPApplication/CSPApplication.csproj
- secure-app-model/keyvault/CSPApplication/packages.config
- secure-app-model/keyvault/PartnerConsent/PartnerConsent.csproj
- secure-app-model/keyvault/PartnerConsent/Web.config
- secure-app-model/keyvault/PartnerConsent/packages.config
Through this pull request the following changes are being made 
* Adding the YAML front to ensure that both the SDK and Secure App Model samples are listed in the new [samples platform](https://docs.microsoft.com/samples)
* Updating the dependencies
> Updating dependencies

- sdk/SdkSamples/Agreements/CreateCustomerAgreement.cs
- sdk/SdkSamples/Agreements/GetAgreementDetails.cs
- sdk/SdkSamples/Agreements/GetAgreementDocument.cs
- sdk/SdkSamples/Agreements/GetAllCustomersAgreements.cs
- sdk/SdkSamples/Agreements/GetCustomerAgreements.cs
- sdk/SdkSamples/Agreements/ImportCustomersAgreement.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
Contains updates to the SDK samples for recent agreement related changes in the API and the latest version of the SDK (1.14.0).
> Customer Agreements related SDK sample updates

- README.md
- sdk/README.md
Through this pull request the documentation is being updated
> Updating the documentation

- sdk/SdkSamples/CustomerProducts/GetCustomerAvailabilitiesByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerAvailabilitiesByTargetSegmentByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerProductByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerProductsByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerProductsByTargetSegmentByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerSkuByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerSkusByReservationScope.cs
- sdk/SdkSamples/CustomerProducts/GetCustomerSkusByTargetSegmentByReservationScope.cs
- sdk/SdkSamples/Products/GetAvailabilitiesByReservationScope.cs
- sdk/SdkSamples/Products/GetAvailabilitiesByTargetSegmentByReservationScope.cs
- sdk/SdkSamples/Products/GetProductByReservationScope.cs
- sdk/SdkSamples/Products/GetProductsByReservationScope.cs
- sdk/SdkSamples/Products/GetProductsByTargetSegmentByReservationScope.cs
- sdk/SdkSamples/Products/GetSkuByReservationScope.cs
- sdk/SdkSamples/Products/GetSkusByReservationScope.cs
- sdk/SdkSamples/Products/GetSkusByTargetSegmentByReservationScope.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
Adding samples for all combinations of optional reservation scope filter parameter for PSA APIs
> Adding scenarios for new reservation scope filter for PSA APIs

- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
Merged my two previous branches automatically by accident so need to revert these two PRs, but build is failing since sdk version is behind, so I need to update the sdk version to complete the revert so I can put in new PRs that will be approved
> Updating sdk version

- sdk/SdkSamples/Compliance/GetAgreementSignatureStatus.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
Added the sample code for Compliance scenarios while using Partner Center SDK.
https://microsoft.visualstudio.com/OSGS/_workitems/edit/24259827
> Added the Compliance scenarios sample app.

- secure-app-model/keyvault/PartnerConsent/PartnerConsent.csproj
- secure-app-model/keyvault/PartnerConsent/Web.config
Through this pull request the binding configuration for the consent application is being updated
[#48](https://github.com/MicrosoftDocs/partner-center-sdk/issues/48)
> Secure app model update

- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/Subscriptions/GetSubscriptionTransitions.cs
- sdk/SdkSamples/Subscriptions/TransitionSubscription.cs
- sdk/SdkSamples/Subscriptions/UpgradeSubscription.cs
- sdk/SdkSamples/packages.config
Adding SDK samples for TransitionSubscription and GetSubscriptionTransitions.
> Adding new transition scenarios to the SDK samples

- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/Subscriptions/UpdateSubscriptionScheduledChange.cs
- sdk/SdkSamples/packages.config
Description
Adding SDK Samples for the Subscription schedule change feature.
> update subscription schedule change sdk samples.

- sdk/SdkSamples/Customers/GetValidationStatus.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
Adding validation sample for `v3.0.0`.
No related issues.
> Add validation sample

- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/Subscriptions/UpdateOverage.cs
> Telco subscription overage api samples

- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/PromotionEligibilities/PostPromotionEligibilities.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
Adding promotion eligibility samples.
Adding promotion eligibilities sample to SDK.
> Adding Promotion ELigibility

- sdk/SdkSamples/NewCommerceMigrations/ValidateAndCreateNewCommerceMigration.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
Add New-Commerce migrations scenarios including migration validation and creation.
> Add NCE Migration scenario.

- nce-bulk-migration-tool/NCEBulkMigrationTool/Models.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/NewCommerceMigrationProvider.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/SubscriptionProvider.cs
> Add autorenew filed to subscription export

- nce-bulk-migration-tool/NCEBulkMigrationTool/NewCommerceMigrationProvider.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/SubscriptionProvider.cs
> Fix failedcustomers export and increase the migration upload limit to 200

- nce-bulk-migration-tool/Readme.md
> Update BAM readme file to include pre-requisites and known issues.

- sdk/SdkSamples/Customers/DeletePartnerCustomerDap.cs
- sdk/SdkSamples/Customers/DeletePartnerCustomerRelationship.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
Added sample code to delete partner customer dap.
> Add Delete partner customer Dap sample.

- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/Subscriptions/UpdateSubscriptionScheduledChange.cs
- sdk/SdkSamples/packages.config
> adding promotion to scheduled change.

- nce-bulk-migration-tool/NCEBulkMigrationTool/CustomerProvider.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/INewCommerceMigrationScheduleProvider.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/Models.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/NewCommerceMigrationProvider.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/NewCommerceMigrationScheduleProvider.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/Program.cs
- nce-bulk-migration-tool/NCEBulkMigrationTool/SubscriptionProvider.cs
> Schedule Migration Integration

- sdk/SdkSamples/Customers/CreateCustomerQualification.cs
- sdk/SdkSamples/Customers/CreateCustomerQualificationWithGCC.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/SelfServePolicies/CreateSelfServePolicies.cs
- sdk/SdkSamples/packages.config
Adding samples for Fall 2022 Partner Center SDK Updates.
> adding samples for fall 2022 updates

- sdk/SdkSamples/AzureEntitlement/CancelAzureEntitlement.cs
- sdk/SdkSamples/AzureEntitlement/GetAzureEntitlement.cs
- sdk/SdkSamples/BasePartnerScenario.cs
- sdk/SdkSamples/Program.cs
- sdk/SdkSamples/SdkSamples.csproj
- sdk/SdkSamples/packages.config
> Azure entitlement get and cancel operations

- MCARefreshBulkAttestationCLITool/.gitignore
- MCARefreshBulkAttestationCLITool/AppSettings.cs
- MCARefreshBulkAttestationCLITool/Http/McaHttpClientExtensions.cs
- MCARefreshBulkAttestationCLITool/Interfaces/ICustomerProvider.cs
- MCARefreshBulkAttestationCLITool/Interfaces/IFileProvider.cs
- MCARefreshBulkAttestationCLITool/Interfaces/ITokenProvider.cs
- MCARefreshBulkAttestationCLITool/MCARefreshBulkAttestationCLITool.csproj
- MCARefreshBulkAttestationCLITool/Models/CustomerAgreementRecord.cs
- MCARefreshBulkAttestationCLITool/Models/FetchCustomerAgreementRecordResponse.cs
- MCARefreshBulkAttestationCLITool/Models/LastAgreementPrimaryContact.cs
- MCARefreshBulkAttestationCLITool/Models/ReAttestationRequest.cs
- MCARefreshBulkAttestationCLITool/Program.cs
- MCARefreshBulkAttestationCLITool/Providers/CsvProvider.cs
- MCARefreshBulkAttestationCLITool/Providers/CustomerProvider.cs
- MCARefreshBulkAttestationCLITool/Providers/TokenProvider.cs
Open sourcing the MCA Refresh Bulk Attestation Tool.
Documentation links to be published shortly.
> Adding the MCA Refresh Bulk Attestation Tool
